language: python
python:
  - 3.8
  - 3.7
  - 3.6

# Python 3.7 currently (early 2019) needs a newer Ubuntu version than the
# default image on Travis.

env:
  global:
    - MPLBACKEND=agg

install:
  - make dev-install
  - pip install codecov

script:
  - make test

after_success: codecov