#!/bin/bash
# script runs subsequent images via hdfsee.py from the stream file.
# Running from args1: stream file, args2: geomfile
for i in $(grep "Image filename" $1| cut -f 3 -d " ")
do
  echo $i
  hdfsee_py  $i  -g $2 -p $1
done
